# Generated by Django 4.2.17 on 2024-12-08 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pasien',
            new_name='TablePasien',
        ),
    ]
