# Generated by Django 4.2.17 on 2024-12-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0002_rename_pasien_tablepasien'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableDokter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('no_telp', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255, unique=True)),
            ],
        ),
    ]
