# Generated by Django 4.2.17 on 2024-12-08 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0003_tabledokter'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableAntrian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_antrian', models.CharField(max_length=200)),
                ('status_antrian', models.CharField(default='Sedang menunggu', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_app.tablepasien')),
            ],
        ),
    ]
