# Generated by Django 4.2.17 on 2024-12-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0004_tableantrian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableantrian',
            name='status_antrian',
            field=models.CharField(choices=[('0', 'Sedang menunggu'), ('1', 'Sudah dipanggil'), ('2', 'Selesai'), ('3', 'Batal')], default='Sedang menunggu', max_length=20),
        ),
    ]
