# Generated by Django 4.2.17 on 2024-12-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0005_alter_tableantrian_status_antrian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableantrian',
            name='id',
        ),
        migrations.AlterField(
            model_name='tableantrian',
            name='no_antrian',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
