# Generated by Django 4.2.17 on 2024-12-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0006_remove_tableantrian_id_alter_tableantrian_no_antrian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableantrian',
            name='no_antrian',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
