# Generated by Django 4.2.17 on 2024-12-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0007_alter_tableantrian_no_antrian'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableantrian',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tableantrian',
            name='no_antrian',
            field=models.CharField(max_length=200),
        ),
    ]
