# Generated by Django 4.2.17 on 2024-12-09 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0010_tableantrian_id_alter_tableantrian_no_antrian'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableantrian',
            name='dokter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pos_app.tabledokter'),
            preserve_default=False,
        ),
    ]
