# Generated by Django 5.1.4 on 2025-01-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0011_tableantrian_dokter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablepasien',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
    ]
